version: '3.4'

services:
  test:
    image: ${DOCKER_REGISTRY-}test
    build:
      context: .
      dockerfile: test/Dockerfile
    depends_on:
      - mssql
  mssql:
    image: 'mcr.microsoft.com/mssql/server:2022-latest'
      
